development:
  sessions:
    default:
      database: cascade_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: cascade_test
      hosts:
        - localhost:27017
